In [ ]:
#Importacion de las librerias necesarias
#Uso del codigo que fue entregado como base del proyecto
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import time
from IPython.display import display
#Configuración para tablas en Jupyter con el fin de mantener una presentacion adecuada y facil legibilidad de los datos
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)
#URL de la API
api_url = 'https://api.yelp.com/v3/businesses/search'
#Credenciales Yelp
clientid = 'GWOCZh9-BmZxtdsAjr7Gug'
apikey = 'FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'
headers = {'Authorization': f'Bearer {apikey}'}
#Ciudades disponibles para el analisis de los datos
ciudades = {
    1: 'Miami',
    2: 'Denver',
    3: 'Boston',
    4: 'San Diego',
    5: 'Dallas',
    6: 'NYC',
    7: 'Seattle',
    8: 'Chicago',
    9: 'Houston',
    10: 'Phoenix'
}
#Primer ciclo while para que al salir de uno de los siguientes ciclos no se interrumpa o acabe el codigo sino que caundo el usuario lo solicite o requiera pueda volver
#Esto con la finalidad de que el usuario pueda explorar los datos de las ciudades por separado y pueda cambiar de ciudad a su comodidad
#El usuario se movera atraves del codigo ingresando los digitos disponibles, cualquier valor fuera de rango le solicitara al usuario que trate nuevamente
#Incluso con valores erroneos el codigo no se interrumpira sino que insistira en recibir una de las respuestas validas, para que el codigo no se rompa mientras el usuario esta usandolo
while True:
    print('Bienvenido, dentro de poco tendra acceso a datos recolectados de varios restaurantes\nPara comodidad estan dividos en ciudades')
    print('\nCiudades disponibles\n')
    for numero, ciudad in ciudades.items():
        print(f'{numero}. {ciudad}')
    print('0. Salir')
    try:
        opcion_ciudad = int(input('\nSeleccione una ciudad: '))
        if opcion_ciudad == 0:
            print('\nHasta luego')
            break
        if opcion_ciudad not in ciudades:
            print('\nCiudad inválida')
            continue
        ciudad = ciudades[opcion_ciudad]
    except ValueError:
        print('\nDebe ingresar un número')
        continue
    print(f'\nConsultando Yelp para {ciudad}...')
    time.sleep(1)
    #Consulta inicial de los datos a solicitud del usuario
    params = {
        'term': 'restaurants',
        'location': ciudad,
        'limit': 1
    }
    #Obtener informacion del api, parametros y encabezados para sufutro uso
    response = requests.get(
        api_url,
        params=params,
        headers=headers
    )
    #Se hara un conteo total de los datos disponibles para la ciudad seleccionada y se le explicara al usurio las limitaciones con los datos
    #Esto mismo con la idea de que apesar de que el usuario no tenga acceso a la mayor parte de los datos sin tendra distintas opciones y datos que lo ayudaran con lo que necesite
    #Se presentaran los datos con el limite de 50 datos que se permiten en 4 diferentes paginas a las que el usuario podra cambiar cuando lo desee
    data = response.json()
    total_restaurantes = data['total']
    limite_api = min(
        total_restaurantes,
        1000
    )
    max_pagina = int(
        np.ceil(limite_api / 50)
    )

    print(f'\nYelp registra aproximadamente '
        f'{total_restaurantes:,} restaurantes en {ciudad}.')
    if total_restaurantes > 1000:
        print('\nPor limitaciones de la API de Yelp '
            'solo pueden consultarse los primeros '
            '200 resultados.')
    print(f'\nRestaurantes disponibles para análisis: '
        f'200')
    print(f'Puede seleccionar páginas entre '
        f'1 y 4.\nCada pagina contara con datos de 50 restaurantes')
    volver_ciudades = False
    #Segundo ciclo while donde el usuario tendra la opcion de analizar los datos desde y hasta la pagina que desee
    #Se hace control de excepciones para que no falle el codigo ni afecte a la experiencia del usuario
    while not volver_ciudades:
        try:
            pagina = int(input('\nSeleccione una página: '))
            if not (1 <= pagina <= max_pagina):
                print('\nPágina inválida')
                continue
        except ValueError:
            print('\nDebe ingresar un número')
            continue
        offset = (pagina - 1) * 50
        params = {
            'term': 'restaurants',
            'location': ciudad,
            'limit': 50,
            'offset': offset
        }
        response = requests.get(
            api_url,
            params=params,
            headers=headers
        )
        data = response.json()
        if 'businesses' not in data:
            print('\nLa API no pudo devolver '
                'resultados para esa página.')
            if 'error' in data:
                print('\nDetalle del error:')
                print(data['error'])
            continue
        negocios = data.get('businesses',[])
        nombres = []
        categorias = []
        ratings = []
        reviews = []
        precios = []
        for negocio in negocios:
            nombres.append(negocio.get('name'))
            categorias.append(
                ', '.join(
                    [
                        categoria['title']
                        for categoria
                        in negocio['categories']
                    ]
                )
            )
            ratings.append(
                negocio.get('rating')
            )
            reviews.append(
                negocio.get('review_count')
            )
            precio = negocio.get(
                'price',
                'No especificado'
            )
            #Correcion de datos analizados incorrectamente para facilidad del usuario
            #Creacion y uso del DataFrame
            if precio == '$$':
                precio = 'Medio'
            elif precio == '$$$':
                precio = 'Alto'
            elif precio == '$$$$':
                precio = 'Muy Alto'
            else:
                precio = 'No especificado'
            precios.append(precio)
        yelp = pd.DataFrame({
            'Nombre': nombres,
            'Categoría': categorias,
            'Rating': ratings,
            'Reseñas': reviews,
            'Precio': precios
        })
        #Tercer ciclo while donde el usuario obtendra accesos a diferentes opciones para la obtencion y el analisis de datos y que al salir pueda volver al menu principal y no detenga el codigo por completo
        #El usuario puede detener el analisis de la ciudad actual para cambiar a otra, hacer los otros analisis que necesite o seguir explorando los 200 datos de diferentes restaurantes que hay por ciudad si asi lo desea!
        #Nuevamente se hace control de excepciones
        while True:
            print(f'\nCiudad seleccionada: {ciudad}')
            print(f'Página cargada: {pagina}')
            print('\n1. Ver restaurantes')
            print('2. Top 10 mejor calificados')
            print('3. Top 10 más reseñados')
            print('4. Categorías más frecuentes')
            print('5. Estadísticas generales')
            print('6. Cargar otra página')
            print('7. Volver al menú principal')
            opcion = input('\nSeleccione una opción: ')
            if opcion == '1':
                max_filas = len(yelp)
                while True:
                    try:
                        print(f'\nRegistros disponibles: '
                            f'0 a {max_filas}')
                        inicio = int(input('Fila inicial: '))
                        fin = int(
                            input('Fila final: '))
                        if not (0 <= inicio < fin <= max_filas):
                            print('\nRango inválido')
                            continue
                        display(yelp.iloc[inicio:fin])
                        while True:
                            accion = input(
                                '\n1. Ver otras filas\n'
                                '2. Volver al menú\n'
                                'Seleccione: '
                            )
                            if accion == '1':
                                break
                            elif accion == '2':
                                raise StopIteration
                            else:
                                print('\nOpción inválida')
                    except ValueError:
                        print('\nDebe ingresar números')
                    except StopIteration:
                        break
            elif opcion == '2':
                top_rating = (yelp.sort_values(by='Rating',ascending=False).head(10).reset_index(drop=True))
                print('\nTop 10 mejor calificados\n')
                display(top_rating)
            elif opcion == '3':
                top_reviews = (yelp.sort_values(by='Reseñas',ascending=False).head(10).reset_index(drop=True))
                print('\nTop 10 más reseñados\n')
                display(top_reviews)
            elif opcion == '4':
                categorias_df = (yelp['Categoría'].str.split(', ').explode().value_counts().reset_index())
                categorias_df.columns = ['Categoría','Cantidad']
                print('\nCategorías más frecuentes '
                    'en los restaurantes cargados\n')
                display(categorias_df.head(10))
            elif opcion == '5':
                estadisticas = pd.DataFrame({
                    'Indicador': [
                        'Restaurantes analizados',
                        'Rating promedio',
                        'Rating máximo',
                        'Rating mínimo',
                        'Promedio de reseñas'
                    ],
                    'Valor': [
                        len(yelp),
                        round(np.mean(yelp['Rating']),2),np.max(yelp['Rating']),
                        np.min(yelp['Rating']),round(np.mean(yelp['Reseñas']),0)
                    ]
                })
                print('\nEstadísticas generales\n')
                display(
                    estadisticas
                )
                restaurante_popular = (yelp.loc[yelp['Reseñas'].idxmax()])
                popular = pd.DataFrame({
                    'Nombre': [restaurante_popular['Nombre']],
                    'Rating': [restaurante_popular['Rating']],
                    'Reseñas': [restaurante_popular['Reseñas']],
                    'Precio': [restaurante_popular['Precio']]
                })
                print('\nRestaurante más popular\n')
                display(popular)
            elif opcion == '6':
                break
            elif opcion == '7':
                volver_ciudades = True
                break
            else:
                print('\nOpción inválida')

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Debe ingresar un número

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Debe ingresar un número

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Debe ingresar un número

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Ciudad inválida

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Debe ingresar un número

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Consultando Yelp para Miami...

Yelp registra aproximadamente 5,800 restaurantes en Miami.

Por limitaciones de la API de Yelp solo pueden consultarse los primeros 1000 resultados.

Restaurantes disponibles para análisis: 1,000
Puede seleccionar páginas entre 1 y 20.

La API no pudo devolver resultados para esa página.

Detalle del error:
{'code': 'VALIDATION_ERROR', 'description': 'Too many results requested, limit+offset must be <= 240.'}

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

La API no pudo devolver resultados para esa página.

Detalle del error:
{'code': 'VALIDATION_ERROR', 'description': 'Too many results requested, limit+offset must be <= 240.'}

La API no pudo devolver resultados para esa página.

Detalle del error:
{'code': 'VALIDATION_ERROR', 'description': 'Too many results requested, limit+offset must be <= 240.'}

Ciudad seleccionada: Miami
Página cargada: 4

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Debe ingresar un número

Página inválida

Página inválida

Página inválida

La API no pudo devolver resultados para esa página.

Detalle del error:
{'code': 'VALIDATION_ERROR', 'description': 'Too many results requested, limit+offset must be <= 240.'}

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Versailles,"Cuban, Coffee & Tea, Sandwiches",4.0,7031,Medio
1,Old's Havana Cuban Bar & Cocina,"Cuban, Bars, Venues & Event Spaces",4.4,3220,Medio
2,Crazy About You,"Mediterranean, Italian, Spanish",4.2,2895,Alto
3,Kyu,Asian Fusion,4.4,2117,Alto
4,Fratellino,Italian,4.8,1915,Alto
5,Lung Yai Thai Tapas,"Tapas/Small Plates, Thai",4.0,1814,Medio
6,Bombay Darbar,Indian,4.5,1713,Medio
7,Glass & Vine,"New American, Breakfast & Brunch",4.1,1711,Medio
8,Sanguich,"Cuban, Sandwiches",4.5,1501,Medio
9,Apocalypse BBQ,"Food Trucks, Barbeque, Empanadas",4.4,1180,Medio

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

La API no pudo devolver resultados para esa página.

Detalle del error:
{'code': 'VALIDATION_ERROR', 'description': 'Too many results requested, limit+offset must be <= 240.'}

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

Rango inválido

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
0,Fratellino,Italian,4.8,1915,Alto
1,Old's Havana Cuban Bar & Cocina,"Cuban, Bars, Venues & Event Spaces",4.4,3220,Medio
2,Salty Flame,"Asian Fusion, Steakhouses, Cocktail Bars",4.3,272,No especificado
3,Crazy About You,"Mediterranean, Italian, Spanish",4.2,2895,Alto
4,House of Food Porn,"Sushi Bars, Asian Fusion, Wine Bars",4.8,177,No especificado
5,Bayshore Club Bar & Grill,"Seafood, American, Wine Bars",4.3,1057,Alto
6,Giselle Miami,"Mediterranean, Lounges, Asian Fusion",4.6,507,No especificado
7,Versailles,"Cuban, Coffee & Tea, Sandwiches",4.0,7031,Medio
8,Chef Allen's Farm to Table,"Vegetarian, Food Stands",4.6,14,Alto
9,Capriccio,"Italian, Pizza, Steakhouses",4.5,175,No especificado
10,First Watch,"Breakfast & Brunch, Cafes, American",4.0,517,Medio
11,TastiGo Kitchen,"Chinese, Noodles",4.6,54,No especificado
12,COTE Miami,"Korean, Steakhouses",4.5,1020,Muy Alto
13,Don Maguey Mexican Restaurant,Mexican,4.7,310,Medio
14,Mezquite Taqueria And Michelada Bar,"Mexican, Bars",4.9,15,No especificado
15,China Spot Miami,Chinese,5.0,1,No especificado
16,Impressions,Cafes,4.6,12,No especificado
17,Jass Kitchen,"Wine Bars, Turkish, Music Venues",4.5,226,No especificado
18,Sufrat Mediterranean Grill,"Mediterranean, Greek, Lebanese",4.4,160,Medio
19,Frenchie's,French,4.5,270,Medio
20,Apocalypse BBQ,"Food Trucks, Barbeque, Empanadas",4.4,1180,Medio
21,Cove Restaurant,"Hotels, Restaurants",3.1,16,No especificado
22,Grand Public,"American, Bars",4.9,12,No especificado
23,Kyu,Asian Fusion,4.4,2117,Alto
24,Namaste Miami,Indian,4.5,226,Medio
25,Gordon Ramsay Hell's Kitchen,"New American, Steakhouses, Cocktail Bars",4.0,643,Alto
26,Sanguich,"Cuban, Sandwiches",4.5,1501,Medio
27,Corona Beach House,"American, Sports Bars, Salad",4.1,909,Medio
28,Glass & Vine,"New American, Breakfast & Brunch",4.1,1711,Medio
29,Luca Osteria,Italian,4.5,491,Alto
30,La Traila Barbecue,Barbeque,4.0,73,No especificado
31,The Fatty Crab,"Seafood, Cajun/Creole, Sports Bars",4.2,793,Medio
32,STAND,"Cafes, Japanese",5.0,3,No especificado
33,La Carreta Restaurant,Cuban,3.8,749,Medio
34,Bodega Ortega,"Sandwiches, Grocery, Breakfast & Brunch",4.8,5,No especificado
35,Sauced ‘N Loadded,"American, Food Trucks",5.0,2,No especificado
36,Sparrow Italia,"Italian, Music Venues",4.4,199,Alto
37,Koko,"Bars, Mexican",4.3,336,No especificado
38,Jrk!,Caribbean,4.5,132,Medio
39,La Terraza,"Venues & Event Spaces, Cuban, Music Venues",4.8,5,No especificado
40,Levant,"Middle Eastern, Mediterranean, Arabic",4.5,155,No especificado
41,107 Taste,"Japanese, Asian Fusion, Noodles",4.6,258,Medio
42,Tailwinds Restaurant & Bar,"Chicken Wings, American, Cocktail Bars",5.0,1,No especificado
43,Bombay Darbar,Indian,4.5,1713,Medio
44,To Be Determined,"Seafood, Asian Fusion, Venezuelan",3.9,47,Muy Alto
45,KPOT Korean BBQ & Hot Pot,"Korean, Barbeque, Hot Pot",4.2,31,No especificado
46,Bunbury,"Argentine, Steakhouses, Cocktail Bars",4.6,976,Alto
47,Lung Yai Thai Tapas,"Tapas/Small Plates, Thai",4.0,1814,Medio
48,The Mexican,Mexican,4.4,18,No especificado
49,Cactus Club Cafe,"New American, Lounges, Cocktail Bars",4.4,95,No especificado

Registros disponibles: 0 a 50

       Nombre Categoría  Rating  Reseñas Precio
0  Fratellino   Italian     4.8     1915   Alto

Opción inválida

Opción inválida

Opción inválida

Opción inválida

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
1,Old's Havana Cuban Bar & Cocina,"Cuban, Bars, Venues & Event Spaces",4.4,3220,Medio

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,China Spot Miami,Chinese,5.0,1,No especificado
1,STAND,"Cafes, Japanese",5.0,3,No especificado
2,Sauced ‘N Loadded,"American, Food Trucks",5.0,2,No especificado
3,Tailwinds Restaurant & Bar,"Chicken Wings, American, Cocktail Bars",5.0,1,No especificado
4,Grand Public,"American, Bars",4.9,12,No especificado
5,Mezquite Taqueria And Michelada Bar,"Mexican, Bars",4.9,15,No especificado
6,House of Food Porn,"Sushi Bars, Asian Fusion, Wine Bars",4.8,177,No especificado
7,Fratellino,Italian,4.8,1915,Alto
8,La Terraza,"Venues & Event Spaces, Cuban, Music Venues",4.8,5,No especificado
9,Bodega Ortega,"Sandwiches, Grocery, Breakfast & Brunch",4.8,5,No especificado

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Versailles,"Cuban, Coffee & Tea, Sandwiches",4.0,7031,Medio
1,Old's Havana Cuban Bar & Cocina,"Cuban, Bars, Venues & Event Spaces",4.4,3220,Medio
2,Crazy About You,"Mediterranean, Italian, Spanish",4.2,2895,Alto
3,Kyu,Asian Fusion,4.4,2117,Alto
4,Fratellino,Italian,4.8,1915,Alto
5,Lung Yai Thai Tapas,"Tapas/Small Plates, Thai",4.0,1814,Medio
6,Bombay Darbar,Indian,4.5,1713,Medio
7,Glass & Vine,"New American, Breakfast & Brunch",4.1,1711,Medio
8,Sanguich,"Cuban, Sandwiches",4.5,1501,Medio
9,Apocalypse BBQ,"Food Trucks, Barbeque, Empanadas",4.4,1180,Medio

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Categorías más frecuentes en los restaurantes cargados

       Categoría  Cantidad
0   Asian Fusion         6
1       American         6
2        Italian         5
3          Cuban         5
4    Steakhouses         5
5  Cocktail Bars         5
6           Bars         4
7  Mediterranean         4
8        Mexican         4
9      Wine Bars         3

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Estadísticas generales

                 Indicador   Valor
0  Restaurantes analizados   50.00
1          Rating promedio    4.43
2            Rating máximo    5.00
3            Rating mínimo    3.10
4      Promedio de reseñas  721.00

Restaurante más popular

       Nombre  Rating  Reseñas Precio
0  Versailles     4.0     7031  Medio

Ciudad seleccionada: Miami
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
0,Dumplings Mi Amor,"Dim Sum, Pan Asian",4.5,138,No especificado
1,Casa Xabi,"Basque, Bars",4.3,78,No especificado
2,Amor di Pasta,Italian,4.3,423,Medio
3,Casa Mariano,Mediterranean,4.7,152,No especificado
4,SOI Thai Street Food,Thai,4.8,54,No especificado
5,Certo Italian Restaurant,"Italian, Pizza, Venues & Event Spaces",4.7,429,Medio
6,Rusty Pelican - Miami,"Seafood, New American, Venues & Event Spaces",3.9,3110,Alto
7,Casa Juan Restaurant,"Latin American, Cuban",3.9,298,Medio
8,Red Rooster Overtown,"Cocktail Bars, New American, Desserts",4.1,1071,Alto
9,Naked Farmer,"New American, Salad, Vegan",4.4,150,Medio
10,The Taco Stand,Mexican,4.5,1733,Medio
11,Buccan,"Seafood, American, Cocktail Bars",4.3,17,No especificado
12,Mofongo,Puerto Rican,4.1,728,Medio
13,Sixty Vines,"New American, Breakfast & Brunch, Wine Bars",4.6,208,No especificado
14,Motek Coral Gables,"Middle Eastern, Mediterranean, Sandwiches",4.3,466,No especificado
15,Cane Fire Grille,"Latin American, Lounges, Caribbean",3.4,50,Alto
16,Amal,"Lebanese, Mediterranean, Arabic",4.1,383,Alto
17,Armstrong Jazz House,"Jazz & Blues, French, Steakhouses",4.0,169,No especificado
18,Grails Miami - Restaurant & Sports Bar,"Sports Bars, New American, Lounges",4.4,780,Medio
19,Yamashiro Miami,"Asian Fusion, Sushi Bars, Japanese",4.1,82,No especificado
20,Greenstreet Cafe,"Breakfast & Brunch, American, Cocktail Bars",4.2,2690,Medio
21,Good Chef Restaurant,"Asian Fusion, Bubble Tea, Ramen",4.7,774,Medio
22,Charlatam,Latin American,4.9,15,No especificado
23,Ghee Indian Kitchen,Indian,4.3,916,Alto
24,Matsuri,"Japanese, Sushi Bars",4.0,931,Medio
25,CHIMBA,"Latin American, Cocktail Bars, Argentine",4.5,128,No especificado
26,Braga Portuguese Restaurant,Portuguese,4.8,81,No especificado
27,Bachour,"Bakeries, New American, Comfort Food",4.4,916,Medio
28,Diced,"Fast Food, Salad, Juice Bars & Smoothies",4.4,598,Medio
29,Loretta & The Butcher,"Argentine, Breakfast & Brunch, Butcher",4.4,333,Medio
30,Peppi’s Steaks & Hoagie’s,"Cheesesteaks, Sandwiches",4.2,9,No especificado
31,Latin Cafe 2000,"Latin American, Cuban",3.6,653,Medio
32,The Korean Chef,Korean,4.5,48,No especificado
33,Baiablu Italian Restaurant,"Salad, Italian, Seafood",4.7,64,No especificado
34,94th Aero Squadron,"New American, Breakfast & Brunch, Caterers",3.6,606,Alto
35,Cafe Versailles,"Cuban, Cafes",3.9,418,No especificado
36,AVA MediterrAegean Coconut Grove,"Mediterranean, Greek",3.8,95,No especificado
37,Cafe La Trova,"Cocktail Bars, Cuban, Venues & Event Spaces",4.4,1298,Alto
38,Mint Beirut,"Mediterranean, Lebanese",4.7,88,No especificado
39,No manches que rico,Tacos,4.0,196,Medio
40,Carbone Vino,"Italian, Desserts, Cocktail Bars",4.3,134,Muy Alto
41,The Bistro,New American,4.7,3,No especificado
42,Homa Persian Cuisine,Persian/Iranian,4.8,46,No especificado
43,Tavolo,"Modern European, Breakfast & Brunch, Sandwiches",5.0,2,No especificado
44,La Camaronera Seafood Joint & Fish Market,"Seafood, Seafood Markets, Food Stands",4.1,1028,Medio
45,La Granja,"Peruvian, Desserts, Seafood",4.0,112,Medio
46,Uchi Miami,"Asian Fusion, Japanese, Sushi Bars",4.6,709,Alto
47,Cafe L'Artisan,Cafes,4.5,2,No especificado
48,Belly Fish,"Sushi Bars, Japanese, Seafood",4.3,107,Medio
49,La Patagonia Argentina,"Latin American, Argentine",4.2,435,Medio

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Tavolo,"Modern European, Breakfast & Brunch, Sandwiches",5.0,2,No especificado
1,Charlatam,Latin American,4.9,15,No especificado
2,Braga Portuguese Restaurant,Portuguese,4.8,81,No especificado
3,Homa Persian Cuisine,Persian/Iranian,4.8,46,No especificado
4,SOI Thai Street Food,Thai,4.8,54,No especificado
5,Mint Beirut,"Mediterranean, Lebanese",4.7,88,No especificado
6,Certo Italian Restaurant,"Italian, Pizza, Venues & Event Spaces",4.7,429,Medio
7,Baiablu Italian Restaurant,"Salad, Italian, Seafood",4.7,64,No especificado
8,The Bistro,New American,4.7,3,No especificado
9,Casa Mariano,Mediterranean,4.7,152,No especificado

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Rusty Pelican - Miami,"Seafood, New American, Venues & Event Spaces",3.9,3110,Alto
1,Greenstreet Cafe,"Breakfast & Brunch, American, Cocktail Bars",4.2,2690,Medio
2,The Taco Stand,Mexican,4.5,1733,Medio
3,Cafe La Trova,"Cocktail Bars, Cuban, Venues & Event Spaces",4.4,1298,Alto
4,Red Rooster Overtown,"Cocktail Bars, New American, Desserts",4.1,1071,Alto
5,La Camaronera Seafood Joint & Fish Market,"Seafood, Seafood Markets, Food Stands",4.1,1028,Medio
6,Matsuri,"Japanese, Sushi Bars",4.0,931,Medio
7,Ghee Indian Kitchen,Indian,4.3,916,Alto
8,Bachour,"Bakeries, New American, Comfort Food",4.4,916,Medio
9,Grails Miami - Restaurant & Sports Bar,"Sports Bars, New American, Lounges",4.4,780,Medio

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Categorías más frecuentes en los restaurantes cargados

            Categoría  Cantidad
0        New American         8
1             Seafood         6
2      Latin American         6
3       Cocktail Bars         6
4       Mediterranean         5
5  Breakfast & Brunch         5
6             Italian         4
7               Cuban         4
8          Sushi Bars         4
9            Japanese         4

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Estadísticas generales

                 Indicador   Valor
0  Restaurantes analizados   50.00
1          Rating promedio    4.32
2            Rating máximo    5.00
3            Rating mínimo    3.40
4      Promedio de reseñas  479.00

Restaurante más popular

                  Nombre  Rating  Reseñas Precio
0  Rusty Pelican - Miami     3.9     3110   Alto

Ciudad seleccionada: Miami
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
0,Drinking Pig BBQ,Barbeque,4.2,60,No especificado
1,Carnicero Steakhouse,Steakhouses,4.1,197,Alto
2,Sweet Dogs,"Hot Dogs, American, Popcorn Shops",4.7,760,No especificado
3,Ossobuco Miami- Steak house,"Steakhouses, Modern European, Seafood",4.6,150,No especificado
4,Eating House,"Beer, Wine & Spirits, American, Italian",4.2,266,Alto
5,Casa Lucas Restaurant,Spanish,5.0,4,No especificado
6,Catch Of The Day,"Seafood, Live/Raw Food, Sports Bars",3.6,737,Medio
7,Ichimi - Gables,"Ramen, Asian Fusion, Izakaya",4.4,1632,Medio
8,Cotoletta,"Salad, Italian",4.6,71,No especificado
9,Urbano Cucina Italiana,Italian,4.4,99,Medio
10,D’Pura Cepa,Puerto Rican,4.3,13,No especificado
11,RO Steakhouse,"Steakhouses, Bars",4.1,70,No especificado
12,Hereford Grill,Steakhouses,4.1,153,Alto
13,Krüs Kitchen,New American,4.3,96,No especificado
14,Slab Daddy Barbecue,Barbeque,4.4,51,No especificado
15,Taqueria Los Potrillos,Mexican,4.4,179,Medio
16,Ristorante Fratelli Milano,Italian,4.4,1427,Medio
17,Taqueria Viva México,Mexican,4.4,537,No especificado
18,Mangrove,"Caribbean, Cocktail Bars, Lounges",4.6,106,No especificado
19,Beauty & The Butcher,"Cocktail Bars, New American",4.2,307,Alto
20,Serafina,"Bars, Italian",4.1,36,No especificado
21,La Bodeguita Espanola,"Grocery, Tapas/Small Plates, Beer, Wine & Spirits",4.0,11,No especificado
22,Chug's Diner,"Cuban, Diners, Caribbean",3.9,652,Medio
23,The Biltmore Brunch,"Breakfast & Brunch, Wedding Planning",3.6,101,Muy Alto
24,Atchana's Homegrown Thai,Thai,4.4,392,Medio
25,Moshi Moshi,"Sushi Bars, Ramen, Izakaya",3.9,648,Medio
26,Habibi Miami,"Mediterranean, Lounges, Arabic",2.9,80,No especificado
27,The B100M,Food Court,4.9,27,No especificado
28,Guys Burger Joint,Burgers,4.3,6,No especificado
29,La Fresa Francesa,"Wine Bars, French",4.6,1035,Medio
30,Brooklyn Dumpling Shop,"Asian Fusion, Dim Sum",4.5,29,No especificado
31,Fugato,"Mediterranean, Italian, Desserts",4.7,130,Alto
32,Miranda Cuisine & Bar,"Latin American, Bars, New American",4.4,111,Medio
33,Manjay Restaurant,Caribbean,4.4,171,Medio
34,Toro Toro,"Steakhouses, Tapas Bars, Cocktail Bars",4.2,1435,Alto
35,SHINGO,"Sushi Bars, Japanese",4.8,54,Muy Alto
36,Fuku,"Salad, Burgers, Chicken Wings",4.2,30,No especificado
37,Narbona Coconut Grove,"Wine Bars, Breakfast & Brunch, Poke",4.1,274,Medio
38,Tinta y Café,"Coffee & Tea, Cuban, Sandwiches",4.3,1097,Medio
39,L'Atelier de Joel Robuchon,French,4.2,209,Muy Alto
40,Bouchon Bistro,"French, Wine Bars, Cocktail Bars",4.0,167,No especificado
41,B Bistro + Bakery,"Bakeries, Breakfast & Brunch, New American",4.4,1216,Medio
42,La Vasca Deli,"Delis, Beer, Wine & Spirits, Spanish",4.6,39,No especificado
43,Rickenbacker Restaurant,New American,3.5,36,Medio
44,Hillstone Restaurant,"New American, Sushi Bars",3.6,1398,Alto
45,Pastis Miami,French,4.4,398,No especificado
46,Tacos El Carnal,Tacos,4.1,334,No especificado
47,Bored Cuban,"Cuban, Desserts, Acai Bowls",4.1,125,Medio
48,Ventanas Restaurant Bar & Lounge,"Latin American, Bars",4.1,11,Medio
49,Pinolandia,"Latin American, Nicaraguan",4.0,384,No especificado

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Casa Lucas Restaurant,Spanish,5.0,4,No especificado
1,The B100M,Food Court,4.9,27,No especificado
2,SHINGO,"Sushi Bars, Japanese",4.8,54,Muy Alto
3,Fugato,"Mediterranean, Italian, Desserts",4.7,130,Alto
4,Sweet Dogs,"Hot Dogs, American, Popcorn Shops",4.7,760,No especificado
5,Ossobuco Miami- Steak house,"Steakhouses, Modern European, Seafood",4.6,150,No especificado
6,Mangrove,"Caribbean, Cocktail Bars, Lounges",4.6,106,No especificado
7,Cotoletta,"Salad, Italian",4.6,71,No especificado
8,La Fresa Francesa,"Wine Bars, French",4.6,1035,Medio
9,La Vasca Deli,"Delis, Beer, Wine & Spirits, Spanish",4.6,39,No especificado

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Ichimi - Gables,"Ramen, Asian Fusion, Izakaya",4.4,1632,Medio
1,Toro Toro,"Steakhouses, Tapas Bars, Cocktail Bars",4.2,1435,Alto
2,Ristorante Fratelli Milano,Italian,4.4,1427,Medio
3,Hillstone Restaurant,"New American, Sushi Bars",3.6,1398,Alto
4,B Bistro + Bakery,"Bakeries, Breakfast & Brunch, New American",4.4,1216,Medio
5,Tinta y Café,"Coffee & Tea, Cuban, Sandwiches",4.3,1097,Medio
6,La Fresa Francesa,"Wine Bars, French",4.6,1035,Medio
7,Sweet Dogs,"Hot Dogs, American, Popcorn Shops",4.7,760,No especificado
8,Catch Of The Day,"Seafood, Live/Raw Food, Sports Bars",3.6,737,Medio
9,Chug's Diner,"Cuban, Diners, Caribbean",3.9,652,Medio

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Categorías más frecuentes en los restaurantes cargados

        Categoría  Cantidad
0         Italian         6
1    New American         6
2     Steakhouses         5
3            Bars         4
4   Cocktail Bars         4
5          French         4
6            Beer         3
7  Wine & Spirits         3
8       Caribbean         3
9           Cuban         3

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Estadísticas generales

                 Indicador   Valor
0  Restaurantes analizados   50.00
1          Rating promedio    4.24
2            Rating máximo    5.00
3            Rating mínimo    2.90
4      Promedio de reseñas  351.00

Restaurante más popular

            Nombre  Rating  Reseñas Precio
0  Ichimi - Gables     4.4     1632  Medio

Ciudad seleccionada: Miami
Página cargada: 3

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Consultando Yelp para Denver...

Yelp registra aproximadamente 4,100 restaurantes en Denver.

Por limitaciones de la API de Yelp solo pueden consultarse los primeros 1000 resultados.

Restaurantes disponibles para análisis: 1,000
Puede seleccionar páginas entre 1 y 20.

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
0,Madeline,Restaurants,4.8,5,No especificado
1,Jack’s on Pearl,"Bars, Steakhouses, Seafood",4.6,237,Alto
2,Tavernetta,Italian,4.5,941,Alto
3,West Saloon & Kitchen,American,4.5,1044,Medio
4,Work & Class,"New American, Latin American, Cocktail Bars",4.5,1884,Medio
5,Culinary Dropout,New American,4.2,1005,Medio
6,Angelo’s Taverna,"Italian, Seafood, Bars",4.4,1988,Medio
7,Rioja,"New American, Spanish, Bars",4.3,2899,Alto
8,Safta,"Middle Eastern, Mediterranean, Burgers",4.5,1056,Alto
9,Point Easy,"New American, Noodles, Cocktail Bars",4.7,89,No especificado
10,Ollie & Park's,"Tapas/Small Plates, Wine Bars, Cocktail Bars",4.3,83,No especificado
11,Ma's Kitchen Next Door,Pan Asian,4.7,67,No especificado
12,Olivia,"Italian, Wine Bars",4.6,298,No especificado
13,Root Down,"New American, Vegan, Vegetarian",4.4,4173,Medio
14,Nana's Dim Sum & Dumplings,Dim Sum,4.5,629,No especificado
15,Pig and Tiger,"Taiwanese, Chicken Wings, Noodles",4.6,49,No especificado
16,Onefold,"Breakfast & Brunch, Cafes",4.3,1232,Medio
17,Guard and Grace Modern Steakhouse,"Steakhouses, Seafood, New American",4.5,2090,Muy Alto
18,Heretik,"Spanish, Basque, French",4.5,2,No especificado
19,The Wolf's Tailor,New American,4.4,329,Muy Alto
20,Fish N Beer,"Seafood, Cocktail Bars",4.6,514,Medio
21,Alma Fonda Fina,Mexican,4.7,274,No especificado
22,Rougarou,"Southern, Cajun/Creole",4.7,44,No especificado
23,Noodles By Nina,"Noodles, Chinese, Cocktail Bars",4.5,103,Medio
24,Mister Oso,"Tacos, Cocktail Bars, Latin American",4.1,480,Medio
25,Corsica,"Wine Bars, French, Italian",4.3,245,No especificado
26,The Porchetta House,"Sandwiches, Breakfast & Brunch",4.7,160,Medio
27,Spitz,"Mediterranean, Greek, American",5.0,3,No especificado
28,Picaera Puerto Rican Cuisine,"Food Trucks, Puerto Rican",4.7,18,No especificado
29,Uchi Denver,"Japanese, Sushi Bars, Asian Fusion",4.5,1114,Muy Alto
30,Steuben's Uptown,"Diners, Breakfast & Brunch, Cocktail Bars",4.0,3457,Medio
31,Lucina Eatery & Bar,"Latin American, Spanish",4.7,162,Alto
32,Pete's Kitchen,"Greek, American, Diners",3.9,958,Medio
33,Painted RiNo Kitchen + Bar,"Bars, Breakfast & Brunch, New American",4.3,9,No especificado
34,Sauvage,"Food Trucks, Cajun/Creole",4.3,12,No especificado
35,Nocturne,"Jazz & Blues, New American, Cocktail Bars",4.6,420,Alto
36,Hillstone Restaurant,"New American, Sushi Bars",3.7,765,Alto
37,The Greenwich Denver,"Desserts, Cocktail Bars, Italian",4.4,183,No especificado
38,A5 Steakhouse,"Steakhouses, Salad",4.3,302,No especificado
39,Fox And The Hen,Breakfast & Brunch,4.4,396,Medio
40,Potager,New American,3.8,496,Alto
41,Denver Biscuit Co. - Colfax,"Sandwiches, Breakfast & Brunch",4.5,4992,Medio
42,Nola Voodoo Tavern,"Cafes, Bars, Seafood",4.5,329,Medio
43,Dear Emilia,Italian,4.7,16,No especificado
44,Barcelona Wine Bar RiNo,"Tapas/Small Plates, Wine Bars, Spanish",4.3,1239,Medio
45,Margot Denver,"New American, Wine Bars",4.7,49,No especificado
46,Kawa Ni,"Izakaya, Noodles, Live/Raw Food",4.5,235,Alto
47,Wildflower,"Cocktail Bars, Cafes",4.6,223,No especificado
48,Yahya's Mediterranean Grill & Pastries,"Mediterranean, Middle Eastern, Greek",4.6,677,Medio
49,Chubby Cattle Hotpot & Sushi - Denver,"Hot Pot, Sushi Bars, Barbeque",4.2,1644,Alto

Registros disponibles: 0 a 50

     Nombre    Categoría  Rating  Reseñas           Precio
0  Madeline  Restaurants     4.8        5  No especificado

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Spitz,"Mediterranean, Greek, American",5.0,3,No especificado
1,Madeline,Restaurants,4.8,5,No especificado
2,Ma's Kitchen Next Door,Pan Asian,4.7,67,No especificado
3,Dear Emilia,Italian,4.7,16,No especificado
4,Picaera Puerto Rican Cuisine,"Food Trucks, Puerto Rican",4.7,18,No especificado
5,Lucina Eatery & Bar,"Latin American, Spanish",4.7,162,Alto
6,Rougarou,"Southern, Cajun/Creole",4.7,44,No especificado
7,The Porchetta House,"Sandwiches, Breakfast & Brunch",4.7,160,Medio
8,Alma Fonda Fina,Mexican,4.7,274,No especificado
9,Point Easy,"New American, Noodles, Cocktail Bars",4.7,89,No especificado

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Denver Biscuit Co. - Colfax,"Sandwiches, Breakfast & Brunch",4.5,4992,Medio
1,Root Down,"New American, Vegan, Vegetarian",4.4,4173,Medio
2,Steuben's Uptown,"Diners, Breakfast & Brunch, Cocktail Bars",4.0,3457,Medio
3,Rioja,"New American, Spanish, Bars",4.3,2899,Alto
4,Guard and Grace Modern Steakhouse,"Steakhouses, Seafood, New American",4.5,2090,Muy Alto
5,Angelo’s Taverna,"Italian, Seafood, Bars",4.4,1988,Medio
6,Work & Class,"New American, Latin American, Cocktail Bars",4.5,1884,Medio
7,Chubby Cattle Hotpot & Sushi - Denver,"Hot Pot, Sushi Bars, Barbeque",4.2,1644,Alto
8,Barcelona Wine Bar RiNo,"Tapas/Small Plates, Wine Bars, Spanish",4.3,1239,Medio
9,Onefold,"Breakfast & Brunch, Cafes",4.3,1232,Medio

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Categorías más frecuentes en los restaurantes cargados

            Categoría  Cantidad
0        New American        12
1       Cocktail Bars        10
2             Italian         6
3  Breakfast & Brunch         6
4                Bars         5
5             Seafood         5
6           Wine Bars         5
7             Spanish         4
8             Noodles         4
9         Steakhouses         3

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Estadísticas generales

                 Indicador   Valor
0  Restaurantes analizados   50.00
1          Rating promedio    4.45
2            Rating máximo    5.00
3            Rating mínimo    3.70
4      Promedio de reseñas  792.00

Restaurante más popular

                        Nombre  Rating  Reseñas Precio
0  Denver Biscuit Co. - Colfax     4.5     4992  Medio

Ciudad seleccionada: Denver
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Registros disponibles: 0 a 50

,Nombre,Categoría,Rating,Reseñas,Precio
0,Brutø,"Tapas/Small Plates, Tacos, Cafes",4.3,145,No especificado
1,Happy Camper,"Pizza, Bars",4.2,1221,Medio
2,Olive & Finch,"New American, Breakfast & Brunch, Cafes",4.2,940,Medio
3,Florence Supper Club,Italian,4.2,36,No especificado
4,Revival Denver Public House,"Cocktail Bars, American, Soup",4.2,232,No especificado
5,Acova,"New American, Gluten-Free, Cocktail Bars",4.3,720,Medio
6,Pony Up,"Sandwiches, Cocktail Bars, New American",4.6,468,Medio
7,Kkoki Korean BBQ,"Korean, Barbeque",4.7,90,No especificado
8,Brasserie Brixton,French,4.4,162,No especificado
9,Jax Fish House & Oyster Bar,"Seafood, New American, Live/Raw Food",4.3,1275,Medio

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,30Forth Kitchen,"New American, Pop-Up Restaurants",5.0,6,No especificado
1,Carne - Argentina Street Food,"Sandwiches, Argentine, Empanadas",4.8,111,Medio
2,Urban Burma,"Burmese, Asian Fusion",4.8,437,Medio
3,Kkoki Korean BBQ,"Korean, Barbeque",4.7,90,No especificado
4,Champagne Tiger,"French, American, Cocktail Bars",4.6,68,No especificado
5,Chicken Riot,Chicken Shop,4.6,11,No especificado
6,Kealoha's BBQ,"Barbeque, Hawaiian, Food Stands",4.6,108,Medio
7,Pony Up,"Sandwiches, Cocktail Bars, New American",4.6,468,Medio
8,Ni Tuyo,"Tacos, Cocktail Bars",4.6,190,Medio
9,Stowaway Kitchen,"Breakfast & Brunch, Cafes",4.5,477,Medio

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Linger,"Asian Fusion, Breakfast & Brunch, Bars",4.1,4396,Medio
1,Savina's,"Mexican, Salad, Cocktail Bars",4.1,2206,Medio
2,Four Friends Kitchen,"Southern, Breakfast & Brunch",4.3,2176,Medio
3,Jelly,"New American, Breakfast & Brunch, Coffee & Tea",4.0,2113,Medio
4,Tupelo Honey Southern Kitchen & Bar,"Southern, Breakfast & Brunch, American",4.1,1551,Medio
5,Mercantile,New American,4.2,1417,Medio
6,Panzano,"Italian, Bars, Breakfast & Brunch",4.3,1308,Alto
7,Jax Fish House & Oyster Bar,"Seafood, New American, Live/Raw Food",4.3,1275,Medio
8,Happy Camper,"Pizza, Bars",4.2,1221,Medio
9,Cuba Cuba Cafe & Bar,"Cuban, Caribbean",4.4,1017,Medio

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Categorías más frecuentes en los restaurantes cargados

            Categoría  Cantidad
0        New American        13
1       Cocktail Bars        12
2  Breakfast & Brunch        11
3                Bars         6
4            American         6
5             Italian         5
6           Wine Bars         5
7               Cafes         3
8          Sandwiches         3
9              French         3

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Estadísticas generales

                 Indicador   Valor
0  Restaurantes analizados   50.00
1          Rating promedio    4.36
2            Rating máximo    5.00
3            Rating mínimo    3.90
4      Promedio de reseñas  593.00

Restaurante más popular

   Nombre  Rating  Reseñas Precio
0  Linger     4.1     4396  Medio

Ciudad seleccionada: Denver
Página cargada: 2

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Consultando Yelp para Phoenix...

Yelp registra aproximadamente 3,000 restaurantes en Phoenix.

Por limitaciones de la API de Yelp solo pueden consultarse los primeros 1000 resultados.

Restaurantes disponibles para análisis: 1,000
Puede seleccionar páginas entre 1 y 20.

Ciudad seleccionada: Phoenix
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 mejor calificados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Pretty Penny,"Cocktail Bars, Seafood, Steakhouses",4.9,90,No especificado
1,Vecina,"Latin American, New American",4.7,446,Medio
2,Orchard Tavern,"Gastropubs, Bars",4.7,164,No especificado
3,Let’s Toast,"Korean, Food Trucks, Sandwiches",4.6,42,No especificado
4,Industry Standard,"New American, Cocktail Bars",4.6,103,Medio
5,Urban Fraiche Restaurant,Mediterranean,4.6,120,No especificado
6,Glai Baan,Thai,4.6,1547,Medio
7,théa,"Mediterranean, Cocktail Bars, Desserts",4.6,635,Alto
8,Bobby Q,"Barbeque, New American",4.5,5368,Medio
9,Tesota,"Comfort Food, Bars, Pizza",4.5,302,No especificado

Ciudad seleccionada: Phoenix
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Top 10 más reseñados

,Nombre,Categoría,Rating,Reseñas,Precio
0,Bobby Q,"Barbeque, New American",4.5,5368,Medio
1,The Arrogant Butcher,"American, Seafood, Cocktail Bars",4.0,3626,Medio
2,Cibo,"Pizza, Italian, Sandwiches",4.4,3084,Medio
3,Culinary Dropout,New American,4.1,2997,Medio
4,The Henry,"New American, Breakfast & Brunch, Coffee & Tea",4.2,2575,Medio
5,Chelsea's Kitchen,New American,4.3,2414,Medio
6,Buck & Rider,"Seafood, Breakfast & Brunch, Live/Raw Food",4.4,2370,Alto
7,The Clever Koi,"Asian Fusion, Ramen, Cocktail Bars",4.2,2201,Alto
8,The Parlor,"Pizza, Italian, Salad",4.4,2128,Medio
9,Windsor,"New American, Breakfast & Brunch, Cocktail Bars",4.3,2022,Medio

Ciudad seleccionada: Phoenix
Página cargada: 1

1. Ver restaurantes
2. Top 10 mejor calificados
3. Top 10 más reseñados
4. Categorías más frecuentes
5. Estadísticas generales
6. Cargar otra página
7. Volver al menú principal

Ciudades disponibles

1. Miami
2. Denver
3. Boston
4. San Diego
5. Dallas
6. NYC
7. Seattle
8. Chicago
9. Houston
10. Phoenix
0. Salir

Hasta luego